apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventoryservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventoryservice
  template:
    metadata:
      labels:
        app: inventoryservice
    spec:
      containers:
      - name: inventoryservice
        image: inventoryservice:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: inventoryservice-service
spec:
  selector:
    app: inventoryservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
