apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderservice
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      containers:
      - name: orderservice
        image: dkeshri/microservice-order-service:latest
        ports:
        - containerPort: 8080
        resources:
            requests:
              cpu: "250m"   # 0.25 vCPU
              memory: "256Mi"
            limits:
              cpu: "500m"   # 0.5 vCPU
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: orderservice-service
spec:
  selector:
    app: orderservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
