version: '3.8'

services:
  opc_publisher:
    image: mcr.microsoft.com/iotedge/opc-publisher:latest
    container_name: opc_publisher
    environment:
      - PUBLISHER_LOGLEVEL=verbose
    volumes:
      - ./pn.json:/appdata/pn.json
    command: ["--pf=/appdata/pn.json", "--aa", "--si=10", "-v","--di=2"]