version: '3.8'

services:
  opc_publisher:
    image: mcr.microsoft.com/iotedge/opc-publisher:latest
    container_name: opc_publisher
    volumes:
      - ./pn.json:/appdata/pn.json
      - ./publisher.log:/appdata/publisher.log:rw
    command: [
      "--pf=/appdata/pn.json", 
      "--aa", 
      "--si=10",
      "--ll=Trace"
      ]