// <auto-generated />
using Dkeshri.DataSync.Common.Data.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dkeshri.DataSync.Common.Migrations.SQL
{
    [DbContext(typeof(DataSyncDbContext))]
    partial class DataSyncDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dkeshri.DataSync.Common.Data.Entities.ChangeTracker", b =>
                {
                    b.Property<long>("ChangeVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasIndex("TableName")
                        .IsUnique();

                    b.ToTable("ChangeTrackers");
                });
#pragma warning restore 612, 618
        }
    }
}
