certificates:
  device_ca_cert: "<path_to_device_ca_cert>"
  device_ca_pk: "<path_to_device_ca_private_key>"
connect:
  management_uri: "http://localhost:15580"
  workload_uri: "http://localhost:15581"
listen:
  management_uri: "http://0.0.0.0:15580"
  workload_uri: "http://0.0.0.0:15581"
moby_runtime:
  uri: "unix:///var/run/docker.sock"
  network: "azure-iot-edge"
  content_trust:
    ca_certs: "<path_to_ca_certs>"
    client_cert: "<path_to_client_cert>"
    client_key: "<path_to_client_key>"
provisioning:
  source: "manual"
