# Build Stage
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /Source
COPY . .
RUN dotnet restore "./TestModule.csproj"
RUN dotnet publish "./TestModule.csproj" --os linux --arch x64 -c Release -o /out

# Serve Stage
FROM mcr.microsoft.com/dotnet/runtime:8.0
WORKDIR /app
COPY --from=build /out .

ENTRYPOINT [ "dotnet", "TestModule.dll" ]