name: DataSync Emitte/Receiver Docker Image CI
# environment variable for this workflow only. available for all jobs.
env:
  version: ${{vars.DATA_SYNC_MAJOR}}.${{vars.DATA_SYNC_MINOR}}.${{github.run_number}}
on:
  # run this workflow manually.
  workflow_dispatch:
  # run workflow automatically when push to master branch.
  # write now I don't want to trigger auto that is why commented.
  # push:
  #   branches: [ "master" ]

jobs:

  build_push_data_sync_emitter:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    env:
      image_name: data-sync-emitter
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build And Push Emitter docker image to docker hub
        working-directory: ./Backend/dotnet/IOT/IOTConcept/DataSync/DataSync.DBChangeEmitterApp
        run: |
          docker build --rm -t ${{secrets.DOCKER_USERNAME}}/${{env.image_name}}:${{env.version}} -t ${{secrets.DOCKER_USERNAME}}/${{env.image_name}}:latest .
          docker push ${{secrets.DOCKER_USERNAME}}/${{env.image_name}} --all-tags

  build_push_data_sync_receiver:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    env:
      image_name: data-sync-receiver
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build And Push Receiver docker image to docker hub
        working-directory: ./Backend/dotnet/IOT/IOTConcept/DataSync/DataSync.DbChangeReceiverApp
        run: |
          docker build --rm -t ${{secrets.DOCKER_USERNAME}}/${{env.image_name}}:${{env.version}} -t ${{secrets.DOCKER_USERNAME}}/${{env.image_name}}:latest .
          docker push ${{secrets.DOCKER_USERNAME}}/${{env.image_name}} --all-tags
